# Generated by Django 4.1.7 on 2023-05-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_meter_location_property_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('paypal', 'PayPal'), ('elcard', 'Элькарт')], default='Не выбрано', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Сумма долга'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice', verbose_name='ID лицевого счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
