# Generated by Django 4.1.7 on 2023-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_reading_reading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
    ]
