# Generated by Django 4.1.7 on 2023-06-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_property_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=10, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user', verbose_name='Электронная почта'),
        ),
    ]
