# Generated by Django 4.1.7 on 2023-06-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_invoice_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='Электронная почта'),
        ),
    ]
