# Generated by Django 4.1.7 on 2023-06-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_property_email_alter_vendor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.property', verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(choices=[('leninskiy', 'Ленинский'), ('oktyabrskiy', 'Октябрьский'), ('sverdlovskiy', 'Свердловский'), ('pervomaiskiy', 'Первомайский')], default='Не выбрано', max_length=50, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='property',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='Полное имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice', verbose_name='ID счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
    ]
