# Generated by Django 4.1.7 on 2023-06-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_property_owner_name_payment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
