# Generated by Django 4.1.7 on 2023-06-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice', verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма платежа'),
        ),
    ]
