# Generated by Django 4.1.7 on 2023-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='meter',
        ),
        migrations.AddField(
            model_name='property',
            name='apartment',
            field=models.CharField(default=0, max_length=50, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='property',
            name='home',
            field=models.CharField(default=0, max_length=50, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='efficiency',
            field=models.FloatField(default=0, verbose_name='КПД'),
        ),
        migrations.AddField(
            model_name='reading',
            name='heat_loss',
            field=models.FloatField(default=0, verbose_name='Теплопотеря'),
        ),
        migrations.AddField(
            model_name='reading',
            name='room_volume',
            field=models.FloatField(default=0, verbose_name='Объем помещения'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_date',
            field=models.DateField(auto_now_add=True, verbose_name='Считывание'),
        ),
    ]
