# Generated by Django 4.1.7 on 2023-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_remove_property_meter_property_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_value',
            field=models.FloatField(auto_created=True, verbose_name='Значение считывания'),
        ),
    ]
