# Generated by Django 4.1.7 on 2023-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_reading_reading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_value',
            field=models.FloatField(verbose_name='Значение считывания'),
        ),
    ]
