# Generated by Django 4.1.7 on 2023-06-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_reading_reading_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='usage',
        ),
        migrations.AddField(
            model_name='cost',
            name='reading',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='billing.reading', verbose_name='ID cxbnsdfybz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.property', verbose_name='ID клиента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_value',
            field=models.FloatField(auto_created=True, blank=True, null=True, verbose_name='Значение считывания'),
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
