# Generated by Django 4.1.7 on 2023-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_cost_rate_alter_cost_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='debt',
            field=models.FloatField(default=0, verbose_name='Задолженность'),
        ),
    ]
