# Generated by Django 4.1.7 on 2023-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_payment_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_payment',
            field=models.FloatField(default=0, verbose_name='Первичная сумма'),
        ),
    ]
