# Generated by Django 4.1.7 on 2023-06-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_payment_first_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='first_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cost', verbose_name='Первичная сумма'),
        ),
    ]
