# Generated by Django 4.1.7 on 2023-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_payment_first_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='number',
        ),
    ]
